services:
  # NodeJS Service
  app-assurmoi-node:
    container_name: "app-assurmoi-API-nodejs"
    build:
      context: ./
      dockerfile: Dockerfile
    command: "npm run dev"
    depends_on:
      app-assurmoi-db:
        condition: service_healthy
      app-assurmoi-mailhog:
        condition: service_started
    links:
      - "app-assurmoi-db:db"
      - "app-assurmoi-mailhog:mailhog"
    environment:
      - NODE_ENV=development
    volumes:
      - "./:/home/app:rw"
    ports:
      - "3000:3000"
    networks:
      - default
    expose:
      - "3000"
    working_dir: "/home/app/assurmoi"
  # SMTP server
  app-assurmoi-mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
  # database
  app-assurmoi-db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: assurmoidb
    healthcheck:
      test:
        ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    volumes:
      - "./db-data:/var/lib/mysql:rw"
  # Database client
  app-assurmoi-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # react native environment
  app-assurmoi-app:
    container_name: "app-assurmoi-reactnative"
    build:
      context: ./
      dockerfile: Dockerfile.front
    command: "npm start"
    environment:
      - NODE_ENV=development
    ports:
      - 8081:8081
    volumes:
      - "./assurmobile:/home/app"
    working_dir: "/home/app/my-app"
