const ROLE_ENUM = Object.freeze({
  ADMIN: 'ADMIN',
  GESTIONNAIRE_PORTEFEUILLE: 'GESTIONNAIRE_PORTEFEUILLE',
  CHARGE_SUIVI: 'CHARGE_SUIVI',
  CHARGE_CLIENTELE: 'CHARGE_CLIENTELE',
  ASSURE: 'ASSURE',
});

const ROLE_VALUES = Object.freeze(Object.values(ROLE_ENUM));

module.exports = { ROLE_ENUM, ROLE_VALUES };
